### ISSUE TITLE
Categories filter buttons disabled on site

### ISSUE THREAD

**Issue by catvec** [kscout/site-reliability-engineering#4]
Potentially related? https://github.com/kscout/kscout.io/issues/50

**Comment by catvec** [comment]
This would fix: https://github.com/kscout/serverless-registry-api/issues/153 for the future, bump priority

**Comment by catvec** [comment]
@janiew What is causing this issue?

**Comment by janiejaffe** [comment]
You guessed right, mismatch between category label and actual category name. 
Solution is to change stored categories to objects with labels and values: display the labels and filter against the values.

**Comment by catvec** [comment]
fixed https://github.com/kscout/kscout.io/pull/51
